### ISSUE TITLE
settings

### ISSUE THREAD

**Issue by cfdbwrbq** [snicoper/django-boilerplate#1]
Hi,
in `base.py` on line 34 
`error_msg = f'Set the {var_name} environment variable'`
must be
`error_msg = r'Set the {var_name} environment variable' ` ?
thanks for boilerplate!

**Comment by snicoper** [comment]
Sorry, I didn't see this message :(

I changed it to 
`error_msg = 'Set the {0} environment variable'.format(var_name)`

`f''` is for Python >= 3.6

https://www.python.org/dev/peps/pep-0498/

Thank you
